##NUMPY BASICS


#CREATING A NUMPY ARRAY AND ITS ATTRIBUTES

In [ ]:
#importing library
import numpy as np

#creating a list
my_list = [1,2,3,4,5]

#chnaging a list into a 1-d numpy array
my_array = np.array(my_list)

#printing the array
print(my_array)


#creating a 0-D numpy array
zero_array = np.array(42)

#printing the array
print(zero_array)

#insted of creating a list on a separate variable we can directly pass a list to .array()function like this
my_array = np.array([1,2,3,4,5])

#printing the 1-D numpy array
print(my_array)

#lets create a 2-D array!
tow_d_array = np.array([[1,2,3],[4,5,6]])

#printing the 2-D array
print(tow_d_array)

#lets create a 3-D array!
three_d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

#printing the 3-D array
print(three_d_array)


[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#lets create an array and see its attributes!
my_array = np.array([[1,2,3],[4,5,6]])
print(my_array) #printing the array
print(my_array.ndim) #printing the dimension of the array
print(my_array.shape) #printing the shape of the array
print(my_array.dtype)  #printing the type of the array
print(my_array.size) #printing the size of the array

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64
6


##ACCESSING AND MANUPULATING ARRAY ELEMENTS


In [ ]:
#lets create a 1-D array and print one of its elements
one_arr = np.array([1,2,3,4,5,6])
print(one_arr[4])

#lets print using negative indexing
print(one_arr[-3])

5
4


In [ ]:
#lets do for a 2-D array
two_arr = np.array([[1,2,3],[4,5,6]])
print(two_arr[1,2])
print(two_arr[0,-1])

6
3


In [ ]:
#lets do for a 3-D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,1,2])

12


##clicing arrays

#someimportant slicing concepts
array[start:end]

array[start:end:steps]


In [ ]:
#slicing array from 0th index to 9th index
my_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_array[1:5])



[2 3 4 5]


In [ ]:
#slicing with steps
my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:9:2])


[1 3 5 7 9]


In [ ]:
#slicing on a 2-D array
my_two_d = np.array([[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]])
print(my_two_d[1,0:6])
print(my_two_d[0,3:6])

[10 11 12 13 14 15]
[4 5 6]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
my_list = [7,14,21,28]

my_array = np.array(my_list)

print(my_list)

[7, 14, 21, 28]


In [ ]:
two_d_array = np.array([[5,10,15],[20,25,30]])
print(my_array.shape)
print(my_array.ndim)

(4,)
1


In [ ]:

import numpy as np

np.zeros((2,3))
arr = np.arange(0, 13, 3)
print(arr)

[ 0  3  6  9 12]


In [ ]:
import numpy as np
arr = np.array([2,4,6,8])
result = arr * 3
print(result)

[ 6 12 18 24]


In [ ]:
import numpy as np
arr = np.array([1,3,5,7,9,11])
print("third element is:", arr[2])
print(arr[1:4])


third element is: 5
[3 5 7]


In [ ]:
#create 1D numpy array with even number from 2 to 10
import numpy as np
arr = np.arange(2 ,11,2)
print(arr)
result = arr + 5
print(result)

[ 2  4  6  8 10]
[ 7  9 11 13 15]


In [ ]:
#create a 2D array with shape (2, 3) and extract its first row
import numpy as np
two_d_array = np.array([[1,3,5],[2,4,6]])
first_row = two_d_array[0]
print(first_row)
print(np.sum(first_row))

[1 3 5]
9


1. Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 10 (inclusive) using np.random.randint. Then, replace all values greater than 5 with 0 and print the modified array.


In [ ]:
#cretaing a 2-D numpy array (3,3) with random integers betn 1 to 10 using np.random.randint and replacing all values greater tha 5 with 0 and printing the modify array
import numpy as np
two_d_array = np.random.randint(1,11,size = (3,3))
print(two_d_array)
two_d_array[two_d_array > 5] = 0
print(two_d_array)


[[5 6 4]
 [9 5 1]
 [9 7 2]]
[[5 0 4]
 [0 5 1]
 [0 0 2]]


2. Create two 1D NumPy arrays: [2, 4, 6, 8] and [1, 3, 5, 7]. Compute the element-wise sum and the dot product of the two arrays. Print both results.


In [ ]:
#creating a 1-D numpy arrays: [2,4,6,8] and [1,3,5,7]. computing the element-wise sum and the dot product of the arrays and printing both results
import numpy as np
my_array = np.array([2,4,6,8])
my_array2 = np.array([1,3,5,7])
print(my_array + my_array2)
print(np.dot(my_array,my_array2))


[ 3  7 11 15]
100


3. Create a 2D NumPy array of shape (4, 3) filled with ones using np.ones. Then, add a 1D array [10, 20, 30] to each row of the 2D array using broadcasting. Print the resulting array.


In [ ]:
#creating a 2-D numpy array shape of (4,3) filled with ones using np.ones then adding a 1D array[10,20,30] to each row of 2D array using broadcasting and printing the result
import numpy as np
two_d_array = np.ones((4,3))
print(two_d_array)
one_d_array = np.array([10,20,30])
result = two_d_array + one_d_array
print(result)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


4. Create a 2D NumPy array [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Extract the second column and compute its mean using np.mean. Then, reshape the original array into a 1D array and print both results.


In [ ]:
#creating a 2-D numpy array [[1,2,3],[4,5,6],[7,8,9]] and extracting a second column and computig its mean using np.array and reshapinig the original arrya into 1D array and printing both result
import numpy as np
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d_array)
second_column = two_d_array[:,1]
print(second_column)
print(np.mean(second_column))
one_d_array = two_d_array.reshape(-1)
print(one_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
5.0
[1 2 3 4 5 6 7 8 9]



5. Create a 1D NumPy array [10, 20, 30, 40, 50, 60]. Use a boolean mask to select elements greater than 30, then square those elements. Print the original array and the modified array.


In [ ]:
#creating a 1D array [10,20,30,40,50,60] and using a boolean mask to select elements greater thann 30 and squaring those elements and printing original and modified arrya
import numpy as np
my_array = np.array([10,20,30,40,50,60])
print(my_array)
boolean_mask = my_array > 30
print(boolean_mask)
my_array[boolean_mask]
print(my_array[boolean_mask])
my_array[boolean_mask] **= 2
print(my_array)

[10 20 30 40 50 60]
[False False False  True  True  True]
[40 50 60]
[  10   20   30 1600 2500 3600]
